{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database initialization failed: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"service":"todo-api","stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /usr/src/app/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","syscall":"connect","timestamp":"2025-04-02 14:38:46"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"Database initialization failed: connect ECONNREFUSED 127.0.0.1:5432","port":5432,"service":"todo-api","stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /usr/src/app/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","syscall":"connect","timestamp":"2025-04-02 14:43:11"}
{"code":"22P02","file":"numutils.c","length":141,"level":"error","line":"232","message":"Failed to fetch duty with id NaN from the database: invalid input syntax for type integer: \"NaN\"","name":"error","routine":"pg_strtoint32","service":"todo-api","severity":"ERROR","stack":"error: invalid input syntax for type integer: \"NaN\"\n    at /usr/src/app/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-04-02 16:41:11","where":"unnamed portal parameter $1 = '...'"}
{"level":"error","message":"DatabaseError: Failed to fetch duty with id NaN","service":"todo-api","timestamp":"2025-04-02 16:41:11"}
{"code":"22P02","file":"numutils.c","length":141,"level":"error","line":"232","message":"Failed to fetch duty with id NaN from the database: invalid input syntax for type integer: \"NaN\"","name":"error","routine":"pg_strtoint32","service":"todo-api","severity":"ERROR","stack":"error: invalid input syntax for type integer: \"NaN\"\n    at /usr/src/app/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-04-02 16:45:10","where":"unnamed portal parameter $1 = '...'"}
{"level":"error","message":"DatabaseError: Failed to fetch duty with id NaN","service":"todo-api","timestamp":"2025-04-02 16:45:10"}
{"level":"error","message":"InvalidIdError: Invalid ID format, ID should be an integer","service":"todo-api","timestamp":"2025-04-02 16:55:27"}
{"level":"error","message":"NotFoundError: Duty with id 1 not found","service":"todo-api","timestamp":"2025-04-02 16:56:42"}
{"level":"error","message":"TypeError: Cannot read properties of undefined (reading 'dutyService')","service":"todo-api","timestamp":"2025-04-02 17:27:54"}
{"code":"42703","file":"analyze.c","length":131,"level":"error","line":"2515","message":"Failed to update duty with id 3 in the database: column \"updated_at\" of relation \"duties\" does not exist","name":"error","position":"30","routine":"transformUpdateTargetList","service":"todo-api","severity":"ERROR","stack":"error: column \"updated_at\" of relation \"duties\" does not exist\n    at /usr/src/app/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-04-02 19:57:57"}
{"level":"error","message":"DutyService: Error updating duty with id 3: Failed to update duty with id 3","name":"DatabaseError","originalError":{"code":"42703","file":"analyze.c","length":131,"line":"2515","name":"error","position":"30","routine":"transformUpdateTargetList","severity":"ERROR"},"service":"todo-api","stack":"DatabaseError: Failed to update duty with id 3\n    at DutyRepository.<anonymous> (/usr/src/app/src/repositories/duty.repository.ts:82:13)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/src/repositories/duty.repository.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","statusCode":500,"timestamp":"2025-04-02 19:57:57"}
{"level":"error","message":"ServiceError: Failed to update duty with id 3","service":"todo-api","timestamp":"2025-04-02 19:57:57"}
{"code":"42703","file":"analyze.c","length":131,"level":"error","line":"2515","message":"Failed to update duty with id 3 in the database: column \"updated_at\" of relation \"duties\" does not exist","name":"error","position":"30","routine":"transformUpdateTargetList","service":"todo-api","severity":"ERROR","stack":"error: column \"updated_at\" of relation \"duties\" does not exist\n    at /usr/src/app/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-04-02 19:58:11"}
{"level":"error","message":"DutyService: Error updating duty with id 3: Failed to update duty with id 3","name":"DatabaseError","originalError":{"code":"42703","file":"analyze.c","length":131,"line":"2515","name":"error","position":"30","routine":"transformUpdateTargetList","severity":"ERROR"},"service":"todo-api","stack":"DatabaseError: Failed to update duty with id 3\n    at DutyRepository.<anonymous> (/usr/src/app/src/repositories/duty.repository.ts:82:13)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/src/repositories/duty.repository.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","statusCode":500,"timestamp":"2025-04-02 19:58:11"}
{"level":"error","message":"ServiceError: Failed to update duty with id 3","service":"todo-api","timestamp":"2025-04-02 19:58:11"}
{"code":"42703","file":"analyze.c","length":131,"level":"error","line":"2515","message":"Failed to update duty with id 3 in the database: column \"updated_at\" of relation \"duties\" does not exist","name":"error","position":"30","routine":"transformUpdateTargetList","service":"todo-api","severity":"ERROR","stack":"error: column \"updated_at\" of relation \"duties\" does not exist\n    at /usr/src/app/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-04-02 19:58:49"}
{"level":"error","message":"DutyService: Error updating duty with id 3: Failed to update duty with id 3","name":"DatabaseError","originalError":{"code":"42703","file":"analyze.c","length":131,"line":"2515","name":"error","position":"30","routine":"transformUpdateTargetList","severity":"ERROR"},"service":"todo-api","stack":"DatabaseError: Failed to update duty with id 3\n    at DutyRepository.<anonymous> (/usr/src/app/src/repositories/duty.repository.ts:82:13)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/src/repositories/duty.repository.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","statusCode":500,"timestamp":"2025-04-02 19:58:49"}
{"level":"error","message":"ServiceError: Failed to update duty with id 3","service":"todo-api","timestamp":"2025-04-02 19:58:49"}
{"code":"42703","file":"analyze.c","length":131,"level":"error","line":"2515","message":"Failed to update duty with id 4 in the database: column \"updated_at\" of relation \"duties\" does not exist","name":"error","position":"30","routine":"transformUpdateTargetList","service":"todo-api","severity":"ERROR","stack":"error: column \"updated_at\" of relation \"duties\" does not exist\n    at /usr/src/app/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-04-02 19:59:17"}
{"level":"error","message":"DutyService: Error updating duty with id 4: Failed to update duty with id 4","name":"DatabaseError","originalError":{"code":"42703","file":"analyze.c","length":131,"line":"2515","name":"error","position":"30","routine":"transformUpdateTargetList","severity":"ERROR"},"service":"todo-api","stack":"DatabaseError: Failed to update duty with id 4\n    at DutyRepository.<anonymous> (/usr/src/app/src/repositories/duty.repository.ts:82:13)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/src/repositories/duty.repository.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","statusCode":500,"timestamp":"2025-04-02 19:59:17"}
{"level":"error","message":"ServiceError: Failed to update duty with id 4","service":"todo-api","timestamp":"2025-04-02 19:59:17"}
{"code":"42703","file":"analyze.c","length":131,"level":"error","line":"2515","message":"Failed to update duty with id 6 in the database: column \"updated_at\" of relation \"duties\" does not exist","name":"error","position":"30","routine":"transformUpdateTargetList","service":"todo-api","severity":"ERROR","stack":"error: column \"updated_at\" of relation \"duties\" does not exist\n    at /usr/src/app/node_modules/pg-pool/index.js:45:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-04-02 20:05:44"}
{"level":"error","message":"DutyService: Error updating duty with id 6: Failed to update duty with id 6","name":"DatabaseError","originalError":{"code":"42703","file":"analyze.c","length":131,"line":"2515","name":"error","position":"30","routine":"transformUpdateTargetList","severity":"ERROR"},"service":"todo-api","stack":"DatabaseError: Failed to update duty with id 6\n    at DutyRepository.<anonymous> (/usr/src/app/src/repositories/duty.repository.ts:82:13)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/src/repositories/duty.repository.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","statusCode":500,"timestamp":"2025-04-02 20:05:44"}
{"level":"error","message":"ServiceError: Failed to update duty with id 6","service":"todo-api","timestamp":"2025-04-02 20:05:44"}
